# Generated by Django 5.2.6 on 2025-09-20 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('overdue', 'overdue'), ('partial', 'partial')], default='pending', max_length=16)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_no', models.IntegerField()),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('misc_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.program')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('khalti', 'khalti'), ('stripe', 'stripe'), ('cash', 'cash')], max_length=32)),
                ('txn_id', models.CharField(blank=True, max_length=256, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('initiated', 'initiated'), ('success', 'success'), ('failed', 'failed'), ('refunded', 'refunded')], default='initiated', max_length=16)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.feeinvoice')),
            ],
        ),
    ]
